This script trains model with positive and negative pairs.

In [2]:
import os
os.environ['FOR_DISABLE_CONSOLE_CTRL_HANDLER'] = '1'

import numpy as np
import pandas as pd
import wandb
import torch
from tqdm import tqdm
from torch.optim.adamw import AdamW
from datetime import datetime
from sentence_transformers import losses, SentenceTransformer
from types import SimpleNamespace

from modules.ModelFunctions import get_ST_model, auto_load_model,encode_concepts
from modules.timed_logger import logger
from modules.metrics import evaluate_embedding_similarity_with_mrr, evaluate_model
from sentence_transformers.util import mine_hard_negatives
from sentence_transformers import InputExample
from datasets import Dataset


def to_hf_dataset(dataset_iterable):
    rows = []
    for item in tqdm(dataset_iterable):
        rows.append({
            "sentence1": item["sentence1"],
            "sentence2": item["sentence2"],
            "label": int(item["label"])   # ensure 0/1
        })
    ds = Dataset.from_list(rows)
    # Ensure correct column order for the loss: [inputs..., label]
    ds = ds.select_columns(["sentence1", "sentence2", "label"])
    return ds

logger.reset_timer()

2025-12-29 18:03:46 - Loading faiss with AVX2 support.
2025-12-29 18:03:46 - Successfully loaded faiss with AVX2 support.

In [3]:

args = {
    "use_wandb": True,
    "model_checkpoint": "none",  # Path to model checkpoint to load (default: none - use HF base model)
    
    "use_relation": True,
    
    "seed": 42,
}

args = SimpleNamespace(**args)

# Initialize Model

In [4]:
logger.log("Loading Model (initial training)")
base_model = 'biobert-base-cased-v1.2'
ST_model = f'models/{base_model}_ST_parentof'


# Load model - use Hugging Face model directly or specified checkpoint
if args.model_checkpoint and args.model_checkpoint != "none":
    model, tokenizer = auto_load_model(args.model_checkpoint)
else:
    model, tokenizer = None, None

if model is None:
    # Load base ST model with special tokens for relation support
    logger.log(f"Loading sentence transformer model: {ST_model}")
    model, tokenizer = auto_load_model(ST_model)

# start_epoch = args.epoch
# start_batch_i = args.batch_i + 1
# start_global_step = args.global_step + 1

2025-12-29 18:03:46 - Loading Model (initial training) (Elapsed: 0.03s, Since last: 0.03s)
2025-12-29 18:03:46 - Loading sentence transformer model: models/biobert-base-cased-v1.2_ST_parentof (Elapsed: 0.03s, Since last: 0.00s)

2025-12-29 18:03:46 - Use pytorch device_name: cuda:0
2025-12-29 18:03:46 - Load pretrained SentenceTransformer: models/biobert-base-cased-v1.2_ST_parentof/init

Loaded latest auto-saved model from: models/biobert-base-cased-v1.2_ST_parentof/init

# Load Training Data

In [5]:
logger.log("Loading training data")

matching_base_path = 'data/matching'
matching_train_path = os.path.join(matching_base_path, 'train')


matching_pairs = pd.read_feather(os.path.join(matching_base_path, 'condition_matching_pairs.feather'))
matching_pairs_train = pd.read_feather(os.path.join(matching_train_path, 'matching_pairs_train.feather'))
matching_pairs_valid = pd.read_feather(os.path.join(matching_train_path, 'matching_pairs_valid.feather'))
matching_pairs_test = pd.read_feather(os.path.join(matching_train_path, 'matching_pairs_test.feather'))

matching_pairs_train.head(3)

2025-12-29 18:03:47 - Loading training data (Elapsed: 0.79s, Since last: 0.76s)

,concept_id,concept_name,source,source_id,type,name_id,name
0,4144990,Achard-Thiers syndrome,OMOP,4144990,synonym,1638163,Achard-Thiers syndrome (disorder)
1,443509,Disorder due to and following burn of wrist an...,OMOP,45599294,nonstd,1482876,"Corrosion of second degree back of right hand,..."
2,4090546,Tuberculous Addison's disease,OMOP,3332816,nonstd,1429543,Tuberculous Addison disease

In [6]:
if args.use_relation:
    relation_base_path = 'data/relation'
    relation_train_path = os.path.join(relation_base_path, 'train')
    relation_train_path = os.path.join(relation_base_path, 'train')
    
    relation_pairs = pd.read_feather(os.path.join(relation_base_path, 'relation_pairs.feather'))
    relation_pairs_train = pd.read_feather(os.path.join(relation_train_path, 'relation_pairs_train.feather'))
    relation_pairs_valid = pd.read_feather(os.path.join(relation_train_path, 'relation_pairs_valid.feather'))
    relation_pairs_test = pd.read_feather(os.path.join(relation_train_path, 'relation_pairs_test.feather'))
    print(relation_pairs_train.head(3))

                                    concept_name  \
0              Detachment of retina of right eye
1  Malignant tumor of thoracic part of esophagus
2                    Benign adenomatous neoplasm

                                                name  concept_id   name_id
0  <|parent of|>Central serous choroidopathy of b...      761145  36712990
1  <|parent of|>B lymphoblastic leukemia/lymphoma...     4092059  36544819
2                       <|parent of|>Adrenal adenoma    40481474   4112987

# Training dataset creation

In [7]:
matching_dataset = Dataset.from_dict({
    "anchor": matching_pairs_train['concept_name'].tolist(),
    "positive": matching_pairs_train['name'].tolist()
})
matching_dataset

Dataset({
    features: ['anchor', 'positive'],
    num_rows: 535158
})

In [8]:
if args.use_relation:
    relation_dataset = Dataset.from_dict({
        "anchor": relation_pairs_train['concept_name'].tolist(),
        "positive": relation_pairs_train['name'].tolist()
    })
    print(relation_dataset)

Dataset({
    features: ['anchor', 'positive'],
    num_rows: 1026046
})

## Combine and Create final training dataset

In [9]:
from datasets import concatenate_datasets
if args.use_relation:
    all_pairs = [matching_dataset, relation_dataset]
else:
    all_pairs = [matching_dataset]
    
ds_all = concatenate_datasets(all_pairs)
ds_all

Dataset({
    features: ['anchor', 'positive'],
    num_rows: 1561204
})

# Validation dataset

In [10]:
from sentence_transformers.evaluation import SentenceEvaluator
# Create a custom evaluator using your existing evaluation function
class CustomMRREvaluator(SentenceEvaluator):
    target_embedding = None
    target_concepts = None
    def __init__(self, query_concepts, query_positive_mapping, name="custom_eval", n_rebuild=10, primary = False):
        self.query_concepts = query_concepts
        self.query_positive_mapping = query_positive_mapping
        self.name = name
        self.n_rebuild = n_rebuild
        self.n_eval = 0
        self.primary = primary
    
    def rebuild_embeddings(self, model):
        type(self).target_embedding = encode_concepts(
            model,
            type(self).target_concepts.concept_name
        ).tolist()
    
    def __call__(self, model, output_path=None, epoch=None, steps=None):
        if self.n_eval % self.n_rebuild == 0 and self.primary:
            self.rebuild_embeddings(model)
        self.n_eval += 1
        if type(self).target_embedding is None:
            raise ValueError("Target embeddings have not been built yet. Call rebuild_embeddings first.")
        # Use your existing evaluation function
        top_df, eval_result = evaluate_model(
            model_name='train',
            model=model,
            query_concepts=self.query_concepts,
            target_concepts=type(self).target_concepts,
            target_embedding = type(self).target_embedding,
            query_positive_mapping=self.query_positive_mapping
        )
        # Return the main metric (MRR) for model selection
        eval_results = {f"{self.name}/{k}": v for k, v in eval_result.items()}
        return eval_results
    
matching_base_path = "data/matching"
target_concepts = pd.read_feather(os.path.join(matching_base_path, 'target_concepts.feather'))
CustomMRREvaluator.target_concepts = target_concepts

In [11]:
matching_pairs.head(3)

,concept_id,concept_name,source,source_id,type,name_id,name
0,42538812,Somatic hallucination,OMOP,42538812,synonym,183881,Somatic hallucination (finding)
1,4084170,Non-allergic anaphylaxis caused by whole blood,OMOP,4084170,synonym,183886,Non-allergic anaphylaxis caused by whole blood...
2,4085531,Scenic visual hallucinations,OMOP,4085531,synonym,183887,Scenic visual hallucinations (finding)

In [12]:
evaluator_matching_valid = CustomMRREvaluator(
    query_concepts=matching_pairs_valid, 
    query_positive_mapping=matching_pairs, 
    name="matching_valid", primary=True)

matching_pairs_train_subset = matching_pairs_train.sample(n=5000, random_state=42)

evaluator_matching_train = CustomMRREvaluator(
    query_concepts=matching_pairs_train_subset, 
    query_positive_mapping=matching_pairs, 
    name="matching_train")

In [13]:
evaluator_matching_valid(model)

Batches: 100%|██████████| 3160/3160 [00:47<00:00, 65.94it/s]
Batches: 100%|██████████| 157/157 [00:02<00:00, 65.35it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00,  4.55it/s]

{'matching_valid/roc_auc': 0.8499580945155872,
 'matching_valid/average_precision': 0.1312437906785383,
 'matching_valid/f1_score': 0.010845563323581229,
 'matching_valid/precision': 0.005452348557562253,
 'matching_valid/recall': 1.0,
 'matching_valid/accuracy': 0.00734,
 'matching_valid/best_hit1': 0.302,
 'matching_valid/best_hit3': 0.365,
 'matching_valid/best_hit5': 0.3944,
 'matching_valid/best_hit10': 0.432,
 'matching_valid/best_hit20': 0.4696,
 'matching_valid/best_hit50': 0.513,
 'matching_valid/best_hit100': 0.5442,
 'matching_valid/best_reciprocal_rank': 0.3457426895304809,
 'matching_valid/worst_hit1': 0.302,
 'matching_valid/worst_hit3': 0.365,
 'matching_valid/worst_hit5': 0.3944,
 'matching_valid/worst_hit10': 0.432,
 'matching_valid/worst_hit20': 0.4696,
 'matching_valid/worst_hit50': 0.513,
 'matching_valid/worst_hit100': 0.5442,
 'matching_valid/worst_reciprocal_rank': 0.3457426895304809}

In [14]:
print(evaluator_matching_train(model))

Batches: 100%|██████████| 157/157 [00:02<00:00, 57.08it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00,  9.99it/s]

{'matching_train/roc_auc': 0.8471158398030503, 'matching_train/average_precision': 0.14545369417111503, 'matching_train/f1_score': 0.011024875621890548, 'matching_train/precision': 0.005542993216336822, 'matching_train/recall': 1.0, 'matching_train/accuracy': 0.00608, 'matching_train/best_hit1': 0.3146, 'matching_train/best_hit3': 0.3734, 'matching_train/best_hit5': 0.4048, 'matching_train/best_hit10': 0.4432, 'matching_train/best_hit20': 0.4802, 'matching_train/best_hit50': 0.519, 'matching_train/best_hit100': 0.554, 'matching_train/best_reciprocal_rank': 0.35708609285878085, 'matching_train/worst_hit1': 0.3146, 'matching_train/worst_hit3': 0.3734, 'matching_train/worst_hit5': 0.4048, 'matching_train/worst_hit10': 0.4432, 'matching_train/worst_hit20': 0.4802, 'matching_train/worst_hit50': 0.519, 'matching_train/worst_hit100': 0.554, 'matching_train/worst_reciprocal_rank': 0.35708609285878085}

In [15]:
if args.use_relation:
    relation_pairs_train_subset = relation_pairs_train.sample(n=5000, random_state=42)
    
    evaluator_relation_train = CustomMRREvaluator(
        query_concepts=relation_pairs_train_subset, 
        query_positive_mapping=relation_pairs, 
        name="relation_train")
    
    evaluator_relation_valid = CustomMRREvaluator(
        query_concepts=relation_pairs_valid, 
        query_positive_mapping=relation_pairs, 
        name="relation_valid")

    print(evaluator_relation_train(model))
    print(evaluator_relation_valid(model))

Batches: 100%|██████████| 154/154 [00:02<00:00, 58.92it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00,  9.28it/s]

{'relation_train/roc_auc': 0.6755804071437971, 'relation_train/average_precision': 0.018196384553025653, 'relation_train/f1_score': 0.01769978172648207, 'relation_train/precision': 0.008928910748896388, 'relation_train/recall': 1.0, 'relation_train/accuracy': 0.00903, 'relation_train/best_hit1': 0.016900834860517206, 'relation_train/best_hit3': 0.09875789045001018, 'relation_train/best_hit5': 0.15577275503970678, 'relation_train/best_hit10': 0.22439421706373447, 'relation_train/best_hit20': 0.3127672571777642, 'relation_train/best_hit50': 0.42190999796375483, 'relation_train/best_hit100': 0.4897169619222154, 'relation_train/best_reciprocal_rank': 0.08226158144912049, 'relation_train/worst_hit1': 0.008144980655670942, 'relation_train/worst_hit3': 0.03746691101608634, 'relation_train/worst_hit5': 0.06699246589289351, 'relation_train/worst_hit10': 0.10914274078599064, 'relation_train/worst_hit20': 0.17817145184280186, 'relation_train/worst_hit50': 0.31459987782529014, 'relation_train/worst_hit100': 0.4878843412746895, 'relation_train/worst_reciprocal_rank': 0.043407427461600825}

Batches: 100%|██████████| 154/154 [00:02<00:00, 65.10it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 13.44it/s]

{'relation_valid/roc_auc': 0.6853654301913548, 'relation_valid/average_precision': 0.018157212120949232, 'relation_valid/f1_score': 0.017230268962714016, 'relation_valid/precision': 0.00869, 'relation_valid/recall': 1.0, 'relation_valid/accuracy': 0.00869, 'relation_valid/best_hit1': 0.019971469329529243, 'relation_valid/best_hit3': 0.09496637456694518, 'relation_valid/best_hit5': 0.14937843896474423, 'relation_valid/best_hit10': 0.22376197269207254, 'relation_valid/best_hit20': 0.3054819645404524, 'relation_valid/best_hit50': 0.41573262685958834, 'relation_valid/best_hit100': 0.4950071326676177, 'relation_valid/best_reciprocal_rank': 0.08376068639569707, 'relation_valid/worst_hit1': 0.012227430201752598, 'relation_valid/worst_hit3': 0.03933156714897086, 'relation_valid/worst_hit5': 0.06745465661300183, 'relation_valid/worst_hit10': 0.11208477684939881, 'relation_valid/worst_hit20': 0.17627878540859995, 'relation_valid/worst_hit50': 0.3117994701446913, 'relation_valid/worst_hit100': 0.493988180150805, 'relation_valid/worst_reciprocal_rank': 0.04670696224486083}

In [16]:
all_evaluators = [evaluator_matching_valid, evaluator_matching_train]
if args.use_relation:
    all_evaluators.extend([evaluator_relation_valid, evaluator_relation_train])

# Model Training settings

In [17]:
from sentence_transformers import SentenceTransformerTrainer, SentenceTransformerTrainingArguments
from sentence_transformers.losses import CachedMultipleNegativesRankingLoss
from sentence_transformers.training_args import BatchSamplers

data_type = 'matching_relation' if args.use_relation else 'matching'
model_first_part = base_model.split('-')[0]
run_name = f"{model_first_part}_{data_type}_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}"
output_dir = f"output/finetune_initial/{run_name}"
max_saves = 4
epoch_num = 10
batch_size = 128

wandb_report_steps = 256
arg_eval_steps = 256
arg_saving_steps = arg_eval_steps * 2

learning_rate = 2e-5
weight_decay = 0.01

# loss = losses.ContrastiveLoss(model=model)
loss = CachedMultipleNegativesRankingLoss(model, mini_batch_size=batch_size)
optimizer = AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay)


wandb.init(
    project="concept_mapping",
    name=run_name
)

# Create training arguments equivalent to your custom training loop
training_args = SentenceTransformerTrainingArguments(
    output_dir=output_dir,
    num_train_epochs=epoch_num,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    warmup_ratio=0.1,
    fp16=False,
    bf16=False,
    learning_rate=learning_rate,
    eval_strategy="steps",
    eval_steps=arg_eval_steps,
    save_strategy="steps",
    save_steps=arg_saving_steps,
    save_total_limit=max_saves,
    logging_steps=wandb_report_steps,
    run_name=run_name,
    batch_sampler=BatchSamplers.NO_DUPLICATES,
    seed=args.seed,
    data_seed=args.seed,
    report_to="wandb" if args.use_wandb else "none",
    remove_unused_columns=False,
    dataloader_drop_last=False,
    dataloader_num_workers=0,  # Avoid multiprocessing issues on Windows
    metric_for_best_model="matching_valid/best_reciprocal_rank",
    greater_is_better=True,
    load_best_model_at_end=True,
)

wandb: Currently logged in as: szwjf08 (szwjf08-utmb) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [ ]:
# Initialize the trainer
trainer = SentenceTransformerTrainer(
    model=model,
    args=training_args,
    train_dataset=ds_all,
    eval_dataset=None,  # Using custom evaluator instead
    loss=loss,
    evaluator=[evaluator_matching_valid, evaluator_matching_train],
    tokenizer=tokenizer,
)

# Start training
logger.log(f"Starting SentenceTransformer training. Model saved to: {output_dir}")
trainer.train(resume_from_checkpoint=args.model_checkpoint if args.model_checkpoint != "none" else None)

# Save the final model
trainer.save_model()
logger.log(f"Training completed. Model saved to {output_dir}")
logger.done()

2025-12-29 18:06:35 - Starting SentenceTransformer training. Model saved to: output/finetune_initial/biobert_matching_relation_2025-12-29_18-06-28 (Elapsed: 169.37s, Since last: 168.57s)

Batches: 100%|██████████| 157/157 [00:02<00:00, 65.72it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]
Batches: 100%|██████████| 157/157 [00:02<00:00, 66.08it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 13.20it/s]
Batches: 100%|██████████| 157/157 [00:02<00:00, 65.51it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
Batches: 100%|██████████| 157/157 [00:02<00:00, 64.67it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 12.78it/s]
2025-12-29 18:09:06 - Saving model checkpoint to output/finetune_initial/biobert_matching_relation_2025-12-29_18-06-28/checkpoint-512
2025-12-29 18:09:06 - Save model to output/finetune_initial/biobert_matching_relation_2025-12-29_18-06-28/checkpoint-512
Batches: 100%|██████████| 157/157 [00:02<00:00, 64.76it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 12.53it/s]
Batches: 100%|██████████| 157/157 [00:02<00:00, 66.25it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 13.04it/s]
Batches: 100%|██████████| 157/157 [00:02<00:00, 60.18it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 11.78it/s]
Batches: 100%|██████████| 157/157 [00:02<00:00, 63.39it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
2025-12-29 18:11:53 - Saving model checkpoint to output/finetune_initial/biobert_matching_relation_2025-12-29_18-06-28/checkpoint-1024
2025-12-29 18:11:53 - Save model to output/finetune_initial/biobert_matching_relation_2025-12-29_18-06-28/checkpoint-1024
Batches: 100%|██████████| 157/157 [00:02<00:00, 65.70it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 12.02it/s]
/home/jiefei/miniconda3/envs/vulcan/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
Batches: 100%|██████████| 157/157 [00:02<00:00, 65.48it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 14.01it/s]
Batches: 100%|██████████| 157/157 [00:02<00:00, 65.05it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 12.07it/s]
/home/jiefei/miniconda3/envs/vulcan/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
Batches: 100%|██████████| 157/157 [00:02<00:00, 64.43it/s]
Searching: 100%|██████████| 1/1 [00:00<00:00, 14.93it/s]
/home/jiefei/miniconda3/envs/vulcan/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
2025-12-29 18:14:51 - Saving model checkpoint to output/finetune_initial/biobert_matching_relation_2025-12-29_18-06-28/checkpoint-1536
2025-12-29 18:14:51 - Save model to output/finetune_initial/biobert_matching_relation_2025-12-29_18-06-28/checkpoint-1536